# Autogenerated wrapper script for X42Plugins_jll for i686-w64-mingw32
export balance_bin, balance_lv2, controlfilter_bin, controlfilter_lv2, matrixmixer_bin, matrixmixer_lv2, mididebug_bin, mididebug_lv2, midifilter_bin, midifilter_lv2, midigen_bin, midigen_lv2, midimap_bin, midimap_lv2, nodelay_bin, nodelay_lv2, onsettrigger_bin, onsettrigger_lv2, phaserotate_bin, phaserotate_lv2, stepseq_bin, stepseq_lv2, stereoroute_bin, stereoroute_lv2, testsignal_bin, testsignal_lv2, xfade_bin, xfade_lv2

using lv2_jll
using FFTW_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("X42Plugins")
JLLWrappers.@declare_library_product(balance_bin, "balance.dll")
JLLWrappers.@declare_file_product(balance_lv2)
JLLWrappers.@declare_library_product(controlfilter_bin, "controlfilter.dll")
JLLWrappers.@declare_file_product(controlfilter_lv2)
JLLWrappers.@declare_library_product(matrixmixer_bin, "matrixmixer.dll")
JLLWrappers.@declare_file_product(matrixmixer_lv2)
JLLWrappers.@declare_library_product(mididebug_bin, "mididebug.dll")
JLLWrappers.@declare_file_product(mididebug_lv2)
JLLWrappers.@declare_library_product(midifilter_bin, "midifilter.dll")
JLLWrappers.@declare_file_product(midifilter_lv2)
JLLWrappers.@declare_library_product(midigen_bin, "midigen.dll")
JLLWrappers.@declare_file_product(midigen_lv2)
JLLWrappers.@declare_library_product(midimap_bin, "midimap.dll")
JLLWrappers.@declare_file_product(midimap_lv2)
JLLWrappers.@declare_library_product(nodelay_bin, "nodelay.dll")
JLLWrappers.@declare_file_product(nodelay_lv2)
JLLWrappers.@declare_library_product(onsettrigger_bin, "onsettrigger.dll")
JLLWrappers.@declare_file_product(onsettrigger_lv2)
JLLWrappers.@declare_library_product(phaserotate_bin, "phaserotate.dll")
JLLWrappers.@declare_file_product(phaserotate_lv2)
JLLWrappers.@declare_library_product(stepseq_bin, "stepseq.dll")
JLLWrappers.@declare_file_product(stepseq_lv2)
JLLWrappers.@declare_library_product(stereoroute_bin, "stereoroute.dll")
JLLWrappers.@declare_file_product(stereoroute_lv2)
JLLWrappers.@declare_library_product(testsignal_bin, "testsignal.dll")
JLLWrappers.@declare_file_product(testsignal_lv2)
JLLWrappers.@declare_library_product(xfade_bin, "xfade.dll")
JLLWrappers.@declare_file_product(xfade_lv2)
function __init__()
    JLLWrappers.@generate_init_header(lv2_jll, FFTW_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        balance_bin,
        "share\\lv2\\balance.lv2\\balance.dll",
        nothing,
    )

    JLLWrappers.@init_file_product(
        balance_lv2,
        "share\\lv2\\balance.lv2\\manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        controlfilter_bin,
        "share\\lv2\\controlfilter.lv2\\controlfilter.dll",
        nothing,
    )

    JLLWrappers.@init_file_product(
        controlfilter_lv2,
        "share\\lv2\\controlfilter.lv2\\manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        matrixmixer_bin,
        "share\\lv2\\matrixmixer.lv2\\matrixmixer.dll",
        nothing,
    )

    JLLWrappers.@init_file_product(
        matrixmixer_lv2,
        "share\\lv2\\matrixmixer.lv2\\manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        mididebug_bin,
        "share\\lv2\\mididebug.lv2\\mididebug.dll",
        nothing,
    )

    JLLWrappers.@init_file_product(
        mididebug_lv2,
        "share\\lv2\\mididebug.lv2\\manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        midifilter_bin,
        "share\\lv2\\midifilter.lv2\\midifilter.dll",
        nothing,
    )

    JLLWrappers.@init_file_product(
        midifilter_lv2,
        "share\\lv2\\midifilter.lv2\\manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        midigen_bin,
        "share\\lv2\\midigen.lv2\\midigen.dll",
        nothing,
    )

    JLLWrappers.@init_file_product(
        midigen_lv2,
        "share\\lv2\\midigen.lv2\\manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        midimap_bin,
        "share\\lv2\\midimap.lv2\\midimap.dll",
        nothing,
    )

    JLLWrappers.@init_file_product(
        midimap_lv2,
        "share\\lv2\\midimap.lv2\\manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        nodelay_bin,
        "share\\lv2\\nodelay.lv2\\nodelay.dll",
        nothing,
    )

    JLLWrappers.@init_file_product(
        nodelay_lv2,
        "share\\lv2\\nodelay.lv2\\manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        onsettrigger_bin,
        "share\\lv2\\onsettrigger.lv2\\onsettrigger.dll",
        nothing,
    )

    JLLWrappers.@init_file_product(
        onsettrigger_lv2,
        "share\\lv2\\onsettrigger.lv2\\manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        phaserotate_bin,
        "share\\lv2\\phaserotate.lv2\\phaserotate.dll",
        nothing,
    )

    JLLWrappers.@init_file_product(
        phaserotate_lv2,
        "share\\lv2\\phaserotate.lv2\\manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        stepseq_bin,
        "share\\lv2\\stepseq_s8n8.lv2\\stepseq.dll",
        nothing,
    )

    JLLWrappers.@init_file_product(
        stepseq_lv2,
        "share\\lv2\\stepseq_s8n8.lv2\\manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        stereoroute_bin,
        "share\\lv2\\stereoroute.lv2\\stereoroute.dll",
        nothing,
    )

    JLLWrappers.@init_file_product(
        stereoroute_lv2,
        "share\\lv2\\stereoroute.lv2\\manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        testsignal_bin,
        "share\\lv2\\testsignal.lv2\\testsignal.dll",
        nothing,
    )

    JLLWrappers.@init_file_product(
        testsignal_lv2,
        "share\\lv2\\testsignal.lv2\\manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        xfade_bin,
        "share\\lv2\\xfade.lv2\\xfade.dll",
        nothing,
    )

    JLLWrappers.@init_file_product(
        xfade_lv2,
        "share\\lv2\\xfade.lv2\\manifest.ttl",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
