# Autogenerated wrapper script for X42Plugins_jll for x86_64-apple-darwin
export balance_bin, balance_lv2, controlfilter_bin, controlfilter_lv2, matrixmixer_bin, matrixmixer_lv2, mididebug_bin, mididebug_lv2, midifilter_bin, midifilter_lv2, midigen_bin, midigen_lv2, midimap_bin, midimap_lv2, nodelay_bin, nodelay_lv2, onsettrigger_bin, onsettrigger_lv2, phaserotate_bin, phaserotate_lv2, stepseq_bin, stepseq_lv2, stereoroute_bin, stereoroute_lv2, testsignal_bin, testsignal_lv2, xfade_bin, xfade_lv2

using lv2_jll
using FFTW_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("X42Plugins")
JLLWrappers.@declare_library_product(balance_bin, "@rpath/balance.dylib")
JLLWrappers.@declare_file_product(balance_lv2)
JLLWrappers.@declare_library_product(controlfilter_bin, "@rpath/controlfilter.dylib")
JLLWrappers.@declare_file_product(controlfilter_lv2)
JLLWrappers.@declare_library_product(matrixmixer_bin, "@rpath/matrixmixer.dylib")
JLLWrappers.@declare_file_product(matrixmixer_lv2)
JLLWrappers.@declare_library_product(mididebug_bin, "@rpath/mididebug.dylib")
JLLWrappers.@declare_file_product(mididebug_lv2)
JLLWrappers.@declare_library_product(midifilter_bin, "@rpath/midifilter.dylib")
JLLWrappers.@declare_file_product(midifilter_lv2)
JLLWrappers.@declare_library_product(midigen_bin, "@rpath/midigen.dylib")
JLLWrappers.@declare_file_product(midigen_lv2)
JLLWrappers.@declare_library_product(midimap_bin, "@rpath/midimap.dylib")
JLLWrappers.@declare_file_product(midimap_lv2)
JLLWrappers.@declare_library_product(nodelay_bin, "@rpath/nodelay.dylib")
JLLWrappers.@declare_file_product(nodelay_lv2)
JLLWrappers.@declare_library_product(onsettrigger_bin, "@rpath/onsettrigger.dylib")
JLLWrappers.@declare_file_product(onsettrigger_lv2)
JLLWrappers.@declare_library_product(phaserotate_bin, "@rpath/phaserotate.dylib")
JLLWrappers.@declare_file_product(phaserotate_lv2)
JLLWrappers.@declare_library_product(stepseq_bin, "@rpath/stepseq.dylib")
JLLWrappers.@declare_file_product(stepseq_lv2)
JLLWrappers.@declare_library_product(stereoroute_bin, "@rpath/stereoroute.dylib")
JLLWrappers.@declare_file_product(stereoroute_lv2)
JLLWrappers.@declare_library_product(testsignal_bin, "@rpath/testsignal.dylib")
JLLWrappers.@declare_file_product(testsignal_lv2)
JLLWrappers.@declare_library_product(xfade_bin, "@rpath/xfade.dylib")
JLLWrappers.@declare_file_product(xfade_lv2)
function __init__()
    JLLWrappers.@generate_init_header(lv2_jll, FFTW_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        balance_bin,
        "share/lv2/balance.lv2/balance.dylib",
        nothing,
    )

    JLLWrappers.@init_file_product(
        balance_lv2,
        "share/lv2/balance.lv2/manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        controlfilter_bin,
        "share/lv2/controlfilter.lv2/controlfilter.dylib",
        nothing,
    )

    JLLWrappers.@init_file_product(
        controlfilter_lv2,
        "share/lv2/controlfilter.lv2/manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        matrixmixer_bin,
        "share/lv2/matrixmixer.lv2/matrixmixer.dylib",
        nothing,
    )

    JLLWrappers.@init_file_product(
        matrixmixer_lv2,
        "share/lv2/matrixmixer.lv2/manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        mididebug_bin,
        "share/lv2/mididebug.lv2/mididebug.dylib",
        nothing,
    )

    JLLWrappers.@init_file_product(
        mididebug_lv2,
        "share/lv2/mididebug.lv2/manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        midifilter_bin,
        "share/lv2/midifilter.lv2/midifilter.dylib",
        nothing,
    )

    JLLWrappers.@init_file_product(
        midifilter_lv2,
        "share/lv2/midifilter.lv2/manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        midigen_bin,
        "share/lv2/midigen.lv2/midigen.dylib",
        nothing,
    )

    JLLWrappers.@init_file_product(
        midigen_lv2,
        "share/lv2/midigen.lv2/manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        midimap_bin,
        "share/lv2/midimap.lv2/midimap.dylib",
        nothing,
    )

    JLLWrappers.@init_file_product(
        midimap_lv2,
        "share/lv2/midimap.lv2/manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        nodelay_bin,
        "share/lv2/nodelay.lv2/nodelay.dylib",
        nothing,
    )

    JLLWrappers.@init_file_product(
        nodelay_lv2,
        "share/lv2/nodelay.lv2/manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        onsettrigger_bin,
        "share/lv2/onsettrigger.lv2/onsettrigger.dylib",
        nothing,
    )

    JLLWrappers.@init_file_product(
        onsettrigger_lv2,
        "share/lv2/onsettrigger.lv2/manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        phaserotate_bin,
        "share/lv2/phaserotate.lv2/phaserotate.dylib",
        nothing,
    )

    JLLWrappers.@init_file_product(
        phaserotate_lv2,
        "share/lv2/phaserotate.lv2/manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        stepseq_bin,
        "share/lv2/stepseq_s8n8.lv2/stepseq.dylib",
        nothing,
    )

    JLLWrappers.@init_file_product(
        stepseq_lv2,
        "share/lv2/stepseq_s8n8.lv2/manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        stereoroute_bin,
        "share/lv2/stereoroute.lv2/stereoroute.dylib",
        nothing,
    )

    JLLWrappers.@init_file_product(
        stereoroute_lv2,
        "share/lv2/stereoroute.lv2/manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        testsignal_bin,
        "share/lv2/testsignal.lv2/testsignal.dylib",
        nothing,
    )

    JLLWrappers.@init_file_product(
        testsignal_lv2,
        "share/lv2/testsignal.lv2/manifest.ttl",
    )

    JLLWrappers.@init_library_product(
        xfade_bin,
        "share/lv2/xfade.lv2/xfade.dylib",
        nothing,
    )

    JLLWrappers.@init_file_product(
        xfade_lv2,
        "share/lv2/xfade.lv2/manifest.ttl",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
